# Generated by Django 2.2.17 on 2021-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка для шаблонизатора'),
        ),
    ]
